### ISSUE TITLE
run app in AOA build flavor not work well

### ISSUE THREAD

**Issue by roger1Lo** [smartdevicelink/hello_sdl_android#22]
When I running app in AOA build flavor version  , it can't work well.
It is fine to connect by usb in code (SdlProxyALM is created well),but it can not get any initial  information in onOnHMIStatus function.
When it running in TCP/IP build flavor version , it can run well . It can receive initial message in onOnHMIStatus function.
Is it a bug in sdl_core when connect by usb (AOA)? It is connected but not send any information.

**Comment by brettywhite** [comment]
@roger1Lo Can we get some idea of your setup? What are you connecting to? SDL version? Android version?

**Comment by roger1Lo** [comment]
I run the sdl_core in ubuntu 14.04 x86 version . And run the hello_sdl_android apk in android smart phone .
I connect the smart phone to  ubuntu .
It can run well when the hello_sdl_android build in tcp/ip flavor version.
But When it build in usb flavor version ,some communication step not work .

**Comment by brettywhite** [comment]
sdl_core does not work out of the box with AOA in Ubuntu, we suggest using TCP/IP in that case, as you have figured out. To get help setting core up for your needs, I suggest using http://slack.smartdevicelink.com and look in the `#core-help` channel. I am going to close this issue as it isn't an issue with the sdl-android library or the hello sdl android app. Thanks!
