### ISSUE TITLE
No such thing as startSdlProxyService() in MainActivity

### ISSUE THREAD

**Issue by kzuraws1** [smartdevicelink/hello_sdl_android#6]
Documentation points to implementing an function similar to startSdlProxyService in the onCreate() of you MainActivity, but the code does not include such example or function within MainActivity.

> Main Activity
> 
> Start the SDLProxy
> 
> In onCreate() in your main activity, you need to add a method to start the Sdl™ service so that the app is listening for a SDL® connection in the case the app is installed while the phone is already connected to SDL®. (Thus, the app will not receive any Bluetooth® events). See the startSdlProxyService() method in MainActivity.java.

From MainActivity:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
```

**Comment by kshala-ford** [comment]
A method like startSdlProxyService() in the main activity called within onCreate() is not necessary in here. On app startup the service is started within the application subclass which is a much better approach than using the activity lifecycle.

hello sdl behavior is as expected. Modify the documentation based on this app not the app based on the documentation.

**Comment by joeygrover** [comment]
Documentation has been updated as well as app. Issue is out of date.
