### ISSUE TITLE
Lack of documentation as to how to get started

### ISSUE THREAD

**Issue by JThinkable** [smartdevicelink/hello_sdl_android#7]
Given this is a hello world app, how do you set up an environment where this works?  For example I'm using a docker-sdl to have something for the app to connect to.  Does that make sense?

Also the android emulator doesn't support bluetooth (http://developer.android.com/tools/devices/emulator.html), so I'm using a TCPConnection instead. 

There's no screenshots or walk through of what to expect so one knows where they went off the rails (or even if they're off the rails) if they think there's a problem.

What does one need at a minimum for this to work?  I'd be glad to supply screen shots and text of my own once this seems to be fully functional for me.

**Comment by brettywhite** [comment]
Hello, 

I know this is an old issue, and we have documentation on it now, located [here](https://smartdevicelink.com/en/guides/android/getting-started/hello-sdl-android/). Therefore I am going to close it.
